# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('regulatedDesignation', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=20)),
                ('size', models.FloatField()),
                ('degreeOfAlcohol', models.FloatField()),
                ('sugarContent', models.CharField(max_length=20)),
                ('evaluation', models.IntegerField()),
                ('inStock', models.BooleanField(default=False)),
                ('cup', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.IntegerField(choices=[('0', 'BEEF'), ('1', 'BREAKFAST'), ('2', 'CHICKEN'), ('3', 'DUCK'), ('4', 'EGGS'), ('5', 'FISH'), ('6', 'FONDUE'), ('7', 'GAME'), ('8', 'LAMB'), ('9', 'LEGUME'), ('10', 'PASTA'), ('11', 'PIZZA'), ('12', 'PORK'), ('13', 'QUICHES'), ('14', 'RICE'), ('15', 'RISOTTO'), ('16', 'SANDWICHES'), ('17', 'SEAFOOD'), ('18', 'TOFU'), ('19', 'TURKEY'), ('20', 'VEAL')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentCellar.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noTransaction', models.CharField(max_length=30)),
                ('requestTime', models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 23, 22, 50, 35, 909168))),
                ('completedTime', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bottle',
            name='grapeVariety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentCellar.GrapeVariety'),
        ),
    ]
