# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0004_auto_20160126_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='degreeOfAlcohol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='evaluation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='regulatedDesignation',
            field=models.CharField(max_length=50),
        ),
    ]
