# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0005_auto_20160126_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='grapeVariety',
        ),
    ]
