# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0006_remove_bottle_grapevariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
