# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0007_bottle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='degreeOfAlcohol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
