# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0008_auto_20160126_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='regulatedDesignation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
