# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelligentCellar', '0010_crawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
